---
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  4xxApiGatewayAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      ActionsEnabled: true
      AlarmName: !Sub "${ServiceName}-${Environment}-http-4XX-gateway-errors"
      AlarmActions:
        - !ImportValue {"Fn::Sub": "${Environment}-alarming-sns-topic"}
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub "${ServiceName}-api${Environment}"
        - Name: Stage
          Value: !Sub "${DeploymentStage}"
      EvaluationPeriods: 1
      MetricName: 4XXErrors
      NameSpace: "AWS/ApiGateway"
      Period: 300
      Statistics: Sum
      Threshold: 10
      ThreatMissingData: missing