---
AWSTemplateFormatVersion: "2010-09-09"

SetfreeApiResource:
  Type: "AWS::ApiGateway::Resource"
  Properties:
    PathPart: setfree
    ParentId: !GetAtt Api.RootResourceId
    RestApiId: !Ref Api

ApiStage:
  Type: "AWS::ApiGateway::Stage"
  Properties:
    DeploymentId: !Ref ApiDeployment
    MehtodSettings:
      - DataTraceEnabled: true
        HttpMethod: "*"
        LoggingLevel: INFO
        ResourcePath: "/*"
    RestApiId: !Ref Api
    StageName: !Ref DeploymentStage