version: 0.1
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm test
  build:
    commands:
      - rm -rf 'node_modules'
      - NODE_ENV=production npm install
artifacts:
  files:
    - 'node_modules/**/*'
    - 'cloudformation/**/*'
    - 'src/**/*'
    - 'imageprocessing.js'
  type: zip