---
AWSTemplateFormatVersion: "2010-09-09"

# manually deploy stack, if repository needs to re-initialized

Resources:
  ImageprocessingRepository:
    Type: "AWS::CodeCommit::Repository"
    Properties:
      RepositoryName: imageprocessing
      RepositoryDescription: Pipeline for imageprocessing service
